
services:
  postgres:
    image: postgres:16-alpine
    container_name: taskman-postgres
    environment:
      POSTGRES_DB: ${TASKMAN_DB_NAME:-taskman}
      POSTGRES_USER: ${TASKMAN_DB_USER:-taskman_user}
      POSTGRES_PASSWORD: ${TASKMAN_DB_PASSWORD:-your_secure_password_here}
    ports:
      - "${TASKMAN_DB_PORT:-5432}:5432"
    volumes:
      - taskman_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TASKMAN_DB_USER:-taskman_user} -d ${TASKMAN_DB_NAME:-taskman}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  taskman_postgres_data: